#!/usr/bin/env python3
"""Regenerates src/block_remap.rs from Pumpkin's generated remap tables.

Pumpkin ships forward tables (server registry -> older client registry) so it can
serve older clients. Axiom's plugin messages are not remapped by the server, so a
client on an older version sends block state ids in its own registry and we need
the inverse. The inverse is almost piecewise-linear, so it is stored as runs of
constant offset instead of a 32k-entry array per version.

Usage: tools/gen_block_remap.py ../pumpkin-src > src/block_remap.rs
"""
import re
import sys

root = sys.argv[1] if len(sys.argv) > 1 else "../pumpkin-src"
path = f"{root}/crates/pumpkin-data/src/generated/block_state_remap.rs"
src = open(path).read()

tables = {
    m.group(1): [int(v) for v in m.group(2).replace("\n", " ").split(",") if v.strip()]
    for m in re.finditer(
        r"BLOCK_STATE_REMAP_V_26_2_TO_(V_[0-9_]+)\s*:\s*&\[u16\]\s*=\s*&\[(.*?)\];", src, re.S
    )
}

body = src.split("pub fn remap_block_state_for_version(", 1)[1]
arms = re.findall(
    r"((?:\s*pumpkin_util::version::JavaMinecraftVersion::V_[0-9_]+\s*\|?)+)=>\s*\{?\s*"
    r"BLOCK_STATE_REMAP_V_26_2_TO_(V_[0-9_]+)",
    body,
)

# WIT renders `v-1-21-9` as `V1219`: segments concatenated, separators dropped.
def wit_name(rust_name):
    return "V" + rust_name[2:].replace("_", "")


def runs_for(forward):
    """Inverts one forward table into (client_start, len, offset) runs."""
    inverse = {}
    for server_id, client_id in enumerate(forward):
        inverse.setdefault(client_id, server_id)
    runs = []
    for client_id in sorted(inverse):
        offset = inverse[client_id] - client_id
        if runs and runs[-1][2] == offset and client_id == runs[-1][0] + runs[-1][1]:
            runs[-1][1] += 1
        else:
            runs.append([client_id, 1, offset])
    return runs


out = sys.stdout.write
out("//! Block state id translation from a client's registry to the server's.\n")
out("//!\n")
out("//! Generated by `tools/gen_block_remap.py` from Pumpkin's\n")
out("//! `block_state_remap.rs`; do not edit.\n\n")
out("use pumpkin_plugin_api::player::JavaMinecraftVersion;\n\n")
out("/// A run of consecutive client state ids whose server ids differ by a constant.\n")
out("pub struct Run {\n    pub start: u16,\n    pub len: u16,\n    pub offset: i32,\n}\n\n")

used = sorted({table for _, table in arms})
for table in used:
    runs = runs_for(tables[table])
    out(f"static T{table}: [Run; {len(runs)}] = [\n")
    for start, length, offset in runs:
        out(f"    Run {{ start: {start}, len: {length}, offset: {offset} }},\n")
    out("];\n\n")

out("/// Returns the translation table for a client version, or `None` when the client\n")
out("/// already speaks the server's registry and no translation is needed.\n")
out("#[must_use]\n")
out("pub const fn table_for(version: JavaMinecraftVersion) -> Option<&'static [Run]> {\n")
out("    match version {\n")
for variants, table in arms:
    names = re.findall(r"V_[0-9_]+", variants)
    pattern = "\n        | ".join(f"JavaMinecraftVersion::{wit_name(n)}" for n in names)
    out(f"        {pattern} => Some(&T{table}),\n")
out("        _ => None,\n    }\n}\n\n")

out("""/// Translates a block state id from a client's registry into the server's.
///
/// Returns `None` for an id the client's registry has but the server's does not,
/// which callers must treat as "leave this block alone" rather than guessing.
#[must_use]
pub fn to_server(table: &[Run], client_id: u16) -> Option<u16> {
    let index = table.partition_point(|run| run.start <= client_id).checked_sub(1)?;
    let run = &table[index];
    if u32::from(client_id) >= u32::from(run.start) + u32::from(run.len) {
        return None;
    }
    u16::try_from(i32::from(client_id) + run.offset).ok()
}
""")
