#!/usr/bin/env python3
"""Regenerates src/permissions.rs from the upstream Java enum.

Usage: tools/gen_permissions.py ../axiom-java-reference > src/permissions.rs
"""
import re
import sys

root = sys.argv[1] if len(sys.argv) > 1 else "../axiom-java-reference"
path = f"{root}/src/main/java/com/moulberry/axiom/restrictions/AxiomPermission.java"
src = open(path).read()
body = src.split("public enum AxiomPermission {", 1)[1].split("public final AxiomPermission parent;")[0]
entries = re.findall(r'^\s*([A-Z][A-Z0-9_]*)\((null|[A-Z][A-Z0-9_]*),\s*"([^"]+)"\)', body, re.M)
idx = {name: i for i, (name, _, _) in enumerate(entries)}

out = sys.stdout.write
out("//! Axiom permission nodes.\n")
out("//!\n")
out("//! Generated by `tools/gen_permissions.py` from `AxiomPermission.java`; do not edit.\n")
out("//!\n")
out("//! `node` doubles as the permission we look up on the player and, as `wire`, the\n")
out("//! name Axiom expects in `axiom:restrictions`. The two differ only for\n")
out("//! `axiom.default`, which goes over the wire as `axiom.*`.\n\n")
out("// Indices are generated for the whole enum; only the ones a handler needs are used.\n")
out("#![allow(dead_code)]\n\n")
out("pub struct Perm {\n")
out("    pub node: &'static str,\n")
out("    pub wire: &'static str,\n")
out("    /// Index into [`PERMS`] of the parent node, if any.\n")
out("    pub parent: Option<usize>,\n")
out("}\n\n")
for name, _, _ in entries:
    out(f"pub const {name}: usize = {idx[name]};\n")
out(f"\npub static PERMS: [Perm; {len(entries)}] = [\n")
for name, parent, node in entries:
    wire = "axiom.*" if name == "DEFAULT" else node
    parent_expr = "None" if parent == "null" else f"Some({idx[parent]})"
    out(f'    Perm {{ node: "{node}", wire: "{wire}", parent: {parent_expr} }},\n')
out("];\n")
