#!/usr/bin/env python3
"""Regenerates block state id translation data from pumpkin-java-multiversion.

That plugin is how Pumpkin serves clients older than itself. It ships forward
tables (the server's registry -> an older client's) and remaps the chunk data it
sends, but passes plugin messages through untouched, so Axiom packets arrive in
the client's registry and anything we send back has to leave in it — both
directions are needed here.

Client -> server collapses into a few dozen constant-offset runs, so it is emitted
as Rust. Server -> client does not (many server states map onto one older state),
so it ships as a flat little-endian u16 array per version, indexed by server state
id, and is embedded with `include_bytes!`.

Usage: tools/gen_block_remap.py ../pumpkin-java-multiversion > src/block_remap.rs
"""
import os
import re
import sys

root = sys.argv[1] if len(sys.argv) > 1 else "../pumpkin-java-multiversion"
path = f"{root}/src/remap/block_state_remap.rs"
asset_dir = "assets/remap"
src = open(path).read()

# Tables are named after the server version they translate from, which moves
# with every Minecraft release.
VERSION = r"V_\d+(?:_\d+)*"
tables = {
    m.group(1): [int(v) for v in m.group(2).replace("\n", " ").split(",") if v.strip()]
    for m in re.finditer(
        rf"BLOCK_STATE_REMAP_{VERSION}_TO_({VERSION})\s*:\s*&\[u16\]\s*=\s*&\[(.*?)\];", src, re.S
    )
}
body = src.split("pub fn remap_block_state_for_version(", 1)[1]
arms = re.findall(
    rf"((?:\s*pumpkin_util::version::JavaMinecraftVersion::{VERSION}\s*\|?)+)=>\s*\{{?\s*"
    rf"BLOCK_STATE_REMAP_{VERSION}_TO_({VERSION})",
    body,
)


# WIT renders `v-1-21-9` as `V1219`: segments concatenated, separators dropped.
def wit_name(rust_name):
    return "V" + rust_name[2:].replace("_", "")


def to_server_runs(forward):
    """Client id -> server id, as runs of constant offset.

    Where several server states collapse onto one client state the lowest server
    id wins, which is how ViaVersion resolves the same ambiguity.
    """
    inverse = {}
    for server_id, client_id in enumerate(forward):
        inverse.setdefault(client_id, server_id)
    runs = []
    for client_id in sorted(inverse):
        offset = inverse[client_id] - client_id
        if runs and runs[-1][2] == offset and client_id == runs[-1][0] + runs[-1][1]:
            runs[-1][1] += 1
        else:
            runs.append([client_id, 1, offset])
    return runs


os.makedirs(asset_dir, exist_ok=True)
used = sorted({table for _, table in arms})
for table in used:
    with open(f"{asset_dir}/{table.lower()}.bin", "wb") as f:
        f.write(b"".join(v.to_bytes(2, "little") for v in tables[table]))

out = sys.stdout.write
out("//! Block state id translation between a client's registry and the server's.\n")
out("//!\n")
out("//! Generated by `tools/gen_block_remap.py` from pumpkin-java-multiversion's\n")
out("//! `block_state_remap.rs`; do not edit. The `assets/remap/*.bin` files are\n")
out("//! generated alongside it.\n\n")
out("use pumpkin_plugin_api::player::JavaMinecraftVersion;\n\n")
out("/// A run of consecutive client state ids whose server ids differ by a constant.\n")
out("pub struct Run {\n    pub start: u16,\n    pub len: u16,\n    pub offset: i32,\n}\n\n")
out("/// Both translation directions for one client version.\n")
out("pub struct Tables {\n")
out("    /// Client registry -> server registry, for ids arriving in Axiom packets.\n")
out("    pub to_server: &'static [Run],\n")
out("    /// Server registry -> client registry, for ids we send back: one\n")
out("    /// little-endian `u16` per server state id.\n")
out("    pub to_client: &'static [u8],\n")
out("}\n\n")

for table in used:
    runs = to_server_runs(tables[table])
    out(f"static S{table}: [Run; {len(runs)}] = [\n")
    for start, length, offset in runs:
        out(f"    Run {{ start: {start}, len: {length}, offset: {offset} }},\n")
    out("];\n")
    out(f'static TABLES{table}: Tables = Tables {{\n')
    out(f"    to_server: &S{table},\n")
    out(f'    to_client: include_bytes!("../assets/remap/{table.lower()}.bin"),\n')
    out("};\n\n")

out("/// Returns the translation tables for a client version, or `None` when the client\n")
out("/// already speaks the server's registry and no translation is needed.\n")
out("#[must_use]\n")
out("pub const fn tables_for(version: JavaMinecraftVersion) -> Option<&'static Tables> {\n")
out("    match version {\n")
for variants, table in arms:
    names = re.findall(r"V_[0-9_]+", variants)
    pattern = "\n        | ".join(f"JavaMinecraftVersion::{wit_name(n)}" for n in names)
    out(f"        {pattern} => Some(&TABLES{table}),\n")
out("        _ => None,\n    }\n}\n\n")

out('''/// Translates a client block state id into the server's registry.
///
/// Returns `None` for an id the client's registry has but the server's does not,
/// which callers must treat as "no equivalent" rather than guessing a replacement.
#[must_use]
pub fn to_server(table: &[Run], client_id: u16) -> Option<u16> {
    let index = table.partition_point(|run| run.start <= client_id).checked_sub(1)?;
    let run = &table[index];
    if u32::from(client_id) >= u32::from(run.start) + u32::from(run.len) {
        return None;
    }
    u16::try_from(i32::from(client_id) + run.offset).ok()
}

/// Translates a server block state id into a client's registry.
#[must_use]
pub fn to_client(table: &[u8], server_id: u16) -> Option<u16> {
    let at = usize::from(server_id) * 2;
    let pair = table.get(at..at + 2)?;
    Some(u16::from_le_bytes([pair[0], pair[1]]))
}
''')
