#!/usr/bin/env python3
"""Regenerates src/biomes.rs from Pumpkin's biome enum.

Axiom names biomes by registry id on the wire; the plugin API exposes them as a
generated enum with no lookup by name, so the mapping is built here.

Usage: tools/gen_biomes.py ../pumpkin-src > src/biomes.rs
"""
import re
import sys

root = sys.argv[1] if len(sys.argv) > 1 else "../pumpkin-src"
src = open(f"{root}/crates/pumpkin-plugin-wit/v0.1/biomes.wit").read()
body = src.split("enum biome {", 1)[1].split("}", 1)[0]
variants = [line.strip().rstrip(",") for line in body.splitlines() if line.strip()]

out = sys.stdout.write
out("//! Biome lookup by registry name.\n")
out("//!\n")
out("//! Generated by `tools/gen_biomes.py` from Pumpkin's `biomes.wit`; do not edit.\n\n")
out("use pumpkin_plugin_api::world::Biome;\n\n")
out("/// Resolves a biome from the registry id Axiom sends, with or without the\n")
out("/// `minecraft:` namespace. Returns `None` for a biome this server does not have.\n")
out("#[must_use]\n")
out("pub fn from_name(name: &str) -> Option<Biome> {\n")
out('    Some(match name.strip_prefix("minecraft:").unwrap_or(name) {\n')
for variant in variants:
    rust = "".join(part.capitalize() for part in variant.split("-"))
    out(f'        "{variant.replace("-", "_")}" => Biome::{rust},\n')
out("        _ => return None,\n    })\n}\n")
