//! Axiom permission nodes.
//!
//! Generated by `tools/gen_permissions.py` from `AxiomPermission.java`; do not edit.
//!
//! `node` doubles as the permission we look up on the player and, as `wire`, the
//! name Axiom expects in `axiom:restrictions`. The two differ only for
//! `axiom.default`, which goes over the wire as `axiom.*`.

// Indices are generated for the whole enum; only the ones a handler needs are used.
#![allow(dead_code)]

pub struct Perm {
    pub node: &'static str,
    pub wire: &'static str,
    /// Index into [`PERMS`] of the parent node, if any.
    pub parent: Option<usize>,
}

pub const ALL: usize = 0;
pub const ENTITY: usize = 1;
pub const ENTITY_SPAWN: usize = 2;
pub const ENTITY_MANIPULATE: usize = 3;
pub const ENTITY_DELETE: usize = 4;
pub const ENTITY_REQUESTDATA: usize = 5;
pub const BLUEPRINT: usize = 6;
pub const BLUEPRINT_UPLOAD: usize = 7;
pub const BLUEPRINT_REQUEST: usize = 8;
pub const BLUEPRINT_MANIFEST: usize = 9;
pub const ANNOTATION: usize = 10;
pub const ANNOTATION_CREATE: usize = 11;
pub const ANNOTATION_CLEARALL: usize = 12;
pub const BUILD_DANGEROUS: usize = 13;
pub const BUILD_DANGEROUS_TICK: usize = 14;
pub const DEFAULT: usize = 15;
pub const USE: usize = 16;
pub const ALLOW_COPYING_OTHER_PLOTS: usize = 17;
pub const CAN_IMPORT_BLOCKS: usize = 18;
pub const CAN_EXPORT_BLOCKS: usize = 19;
pub const CHUNK: usize = 20;
pub const CHUNK_REQUEST: usize = 21;
pub const CHUNK_REQUESTBLOCKENTITY: usize = 22;
pub const BUILD: usize = 23;
pub const BUILD_PLACE: usize = 24;
pub const BUILD_SECTION: usize = 25;
pub const BUILD_NBT: usize = 26;
pub const EDITOR: usize = 27;
pub const EDITOR_USE: usize = 28;
pub const EDITOR_VIEWS: usize = 29;
pub const PLAYER: usize = 30;
pub const PLAYER_BYPASS_MOVEMENT_RESTRICTIONS: usize = 31;
pub const PLAYER_SPEED: usize = 32;
pub const PLAYER_TELEPORT: usize = 33;
pub const PLAYER_GAMEMODE: usize = 34;
pub const PLAYER_GAMEMODE_SURVIVAL: usize = 35;
pub const PLAYER_GAMEMODE_CREATIVE: usize = 36;
pub const PLAYER_GAMEMODE_SPECTATOR: usize = 37;
pub const PLAYER_GAMEMODE_ADVENTURE: usize = 38;
pub const PLAYER_HOTBAR: usize = 39;
pub const PLAYER_SETNOPHYSICALTRIGGER: usize = 40;
pub const WORLD: usize = 41;
pub const WORLD_TIME: usize = 42;
pub const WORLD_PROPERTY: usize = 43;
pub const CAPABILITY: usize = 44;
pub const BULLDOZER: usize = 45;
pub const REPLACE_MODE: usize = 46;
pub const FORCE_PLACE: usize = 47;
pub const NO_UPDATES: usize = 48;
pub const TINKER: usize = 49;
pub const INFINITE_REACH: usize = 50;
pub const FAST_PLACE: usize = 51;
pub const ANGEL_PLACEMENT: usize = 52;
pub const NO_CLIP: usize = 53;
pub const PHANTOM: usize = 54;
pub const TOOL: usize = 55;
pub const TOOL_MAGICSELECT: usize = 56;
pub const TOOL_BOXSELECT: usize = 57;
pub const TOOL_FREEHANDSELECT: usize = 58;
pub const TOOL_LASSOSELECT: usize = 59;
pub const TOOL_RULER: usize = 60;
pub const TOOL_ANNOTATION: usize = 61;
pub const TOOL_PAINTER: usize = 62;
pub const TOOL_NOISEPAINTER: usize = 63;
pub const TOOL_BIOMEPAINTER: usize = 64;
pub const TOOL_GRADIENTPAINTER: usize = 65;
pub const TOOL_SCRIPTBRUSH: usize = 66;
pub const TOOL_FREEHANDDRAW: usize = 67;
pub const TOOL_SCULPTDRAW: usize = 68;
pub const TOOL_ROCK: usize = 69;
pub const TOOL_WELD: usize = 70;
pub const TOOL_MELT: usize = 71;
pub const TOOL_STAMP: usize = 72;
pub const TOOL_TEXT: usize = 73;
pub const TOOL_SHAPE: usize = 74;
pub const TOOL_PATH: usize = 75;
pub const TOOL_MODELLING: usize = 76;
pub const TOOL_FLOODFILL: usize = 77;
pub const TOOL_FLUIDBALL: usize = 78;
pub const TOOL_ELEVATION: usize = 79;
pub const TOOL_SLOPE: usize = 80;
pub const TOOL_SMOOTH: usize = 81;
pub const TOOL_DISTORT: usize = 82;
pub const TOOL_ROUGHEN: usize = 83;
pub const TOOL_SHATTER: usize = 84;
pub const TOOL_EXTRUDE: usize = 85;
pub const TOOL_MODIFY: usize = 86;
pub const BUILDERTOOL: usize = 87;
pub const BUILDERTOOL_MOVE: usize = 88;
pub const BUILDERTOOL_CLONE: usize = 89;
pub const BUILDERTOOL_STACK: usize = 90;
pub const BUILDERTOOL_SMEAR: usize = 91;
pub const BUILDERTOOL_EXTRUDE: usize = 92;
pub const BUILDERTOOL_ERASE: usize = 93;
pub const BUILDERTOOL_SETUPSYMMETRY: usize = 94;

pub static PERMS: [Perm; 95] = [
    Perm { node: "axiom.all", wire: "axiom.all", parent: None },
    Perm { node: "axiom.entity.*", wire: "axiom.entity.*", parent: None },
    Perm { node: "axiom.entity.spawn", wire: "axiom.entity.spawn", parent: Some(1) },
    Perm { node: "axiom.entity.manipulate", wire: "axiom.entity.manipulate", parent: Some(1) },
    Perm { node: "axiom.entity.delete", wire: "axiom.entity.delete", parent: Some(1) },
    Perm { node: "axiom.entity.request_data", wire: "axiom.entity.request_data", parent: Some(1) },
    Perm { node: "axiom.blueprint.*", wire: "axiom.blueprint.*", parent: None },
    Perm { node: "axiom.blueprint.upload", wire: "axiom.blueprint.upload", parent: Some(6) },
    Perm { node: "axiom.blueprint.request", wire: "axiom.blueprint.request", parent: Some(6) },
    Perm { node: "axiom.blueprint.manifest", wire: "axiom.blueprint.manifest", parent: Some(6) },
    Perm { node: "axiom.annotation.*", wire: "axiom.annotation.*", parent: None },
    Perm { node: "axiom.annotation.create", wire: "axiom.annotation.create", parent: Some(10) },
    Perm { node: "axiom.annotation.clear_all", wire: "axiom.annotation.clear_all", parent: Some(10) },
    Perm { node: "axiom.build_dangerous.*", wire: "axiom.build_dangerous.*", parent: None },
    Perm { node: "axiom.build_dangerous.tick", wire: "axiom.build_dangerous.tick", parent: None },
    Perm { node: "axiom.default", wire: "axiom.*", parent: None },
    Perm { node: "axiom.use", wire: "axiom.use", parent: Some(15) },
    Perm { node: "axiom.allow_copying_other_plots", wire: "axiom.allow_copying_other_plots", parent: Some(15) },
    Perm { node: "axiom.can_import_blocks", wire: "axiom.can_import_blocks", parent: Some(15) },
    Perm { node: "axiom.can_export_blocks", wire: "axiom.can_export_blocks", parent: Some(15) },
    Perm { node: "axiom.chunk.*", wire: "axiom.chunk.*", parent: Some(15) },
    Perm { node: "axiom.chunk.request", wire: "axiom.chunk.request", parent: Some(20) },
    Perm { node: "axiom.chunk.request_block_entity", wire: "axiom.chunk.request_block_entity", parent: Some(20) },
    Perm { node: "axiom.build.*", wire: "axiom.build.*", parent: Some(15) },
    Perm { node: "axiom.build.place", wire: "axiom.build.place", parent: Some(23) },
    Perm { node: "axiom.build.section", wire: "axiom.build.section", parent: Some(23) },
    Perm { node: "axiom.build.nbt", wire: "axiom.build.nbt", parent: Some(23) },
    Perm { node: "axiom.editor.*", wire: "axiom.editor.*", parent: Some(15) },
    Perm { node: "axiom.editor.use", wire: "axiom.editor.use", parent: Some(27) },
    Perm { node: "axiom.editor.views", wire: "axiom.editor.views", parent: Some(27) },
    Perm { node: "axiom.player.*", wire: "axiom.player.*", parent: Some(15) },
    Perm { node: "axiom.player.bypass_movement_restrictions", wire: "axiom.player.bypass_movement_restrictions", parent: Some(30) },
    Perm { node: "axiom.player.speed", wire: "axiom.player.speed", parent: Some(30) },
    Perm { node: "axiom.player.teleport", wire: "axiom.player.teleport", parent: Some(30) },
    Perm { node: "axiom.player.gamemode.*", wire: "axiom.player.gamemode.*", parent: Some(30) },
    Perm { node: "axiom.player.gamemode.survival", wire: "axiom.player.gamemode.survival", parent: Some(34) },
    Perm { node: "axiom.player.gamemode.creative", wire: "axiom.player.gamemode.creative", parent: Some(34) },
    Perm { node: "axiom.player.gamemode.spectator", wire: "axiom.player.gamemode.spectator", parent: Some(34) },
    Perm { node: "axiom.player.gamemode.adventure", wire: "axiom.player.gamemode.adventure", parent: Some(34) },
    Perm { node: "axiom.player.hotbar", wire: "axiom.player.hotbar", parent: Some(30) },
    Perm { node: "axiom.player.set_no_physical_trigger", wire: "axiom.player.set_no_physical_trigger", parent: Some(30) },
    Perm { node: "axiom.world.*", wire: "axiom.world.*", parent: Some(15) },
    Perm { node: "axiom.world.time", wire: "axiom.world.time", parent: Some(41) },
    Perm { node: "axiom.world.property", wire: "axiom.world.property", parent: Some(41) },
    Perm { node: "axiom.capability.*", wire: "axiom.capability.*", parent: Some(15) },
    Perm { node: "axiom.capability.bulldozer", wire: "axiom.capability.bulldozer", parent: Some(44) },
    Perm { node: "axiom.capability.replace_mode", wire: "axiom.capability.replace_mode", parent: Some(44) },
    Perm { node: "axiom.capability.force_place", wire: "axiom.capability.force_place", parent: Some(44) },
    Perm { node: "axiom.capability.no_updates", wire: "axiom.capability.no_updates", parent: Some(44) },
    Perm { node: "axiom.capability.tinker", wire: "axiom.capability.tinker", parent: Some(44) },
    Perm { node: "axiom.capability.infinite_reach", wire: "axiom.capability.infinite_reach", parent: Some(44) },
    Perm { node: "axiom.capability.fast_place", wire: "axiom.capability.fast_place", parent: Some(44) },
    Perm { node: "axiom.capability.angel_placement", wire: "axiom.capability.angel_placement", parent: Some(44) },
    Perm { node: "axiom.capability.no_clip", wire: "axiom.capability.no_clip", parent: Some(44) },
    Perm { node: "axiom.capability.phantom", wire: "axiom.capability.phantom", parent: Some(44) },
    Perm { node: "axiom.tool.*", wire: "axiom.tool.*", parent: Some(15) },
    Perm { node: "axiom.tool.magic_select", wire: "axiom.tool.magic_select", parent: Some(55) },
    Perm { node: "axiom.tool.box_select", wire: "axiom.tool.box_select", parent: Some(55) },
    Perm { node: "axiom.tool.freehand_select", wire: "axiom.tool.freehand_select", parent: Some(55) },
    Perm { node: "axiom.tool.lasso_select", wire: "axiom.tool.lasso_select", parent: Some(55) },
    Perm { node: "axiom.tool.ruler", wire: "axiom.tool.ruler", parent: Some(55) },
    Perm { node: "axiom.tool.annotation", wire: "axiom.tool.annotation", parent: Some(55) },
    Perm { node: "axiom.tool.painter", wire: "axiom.tool.painter", parent: Some(55) },
    Perm { node: "axiom.tool.noise_painter", wire: "axiom.tool.noise_painter", parent: Some(55) },
    Perm { node: "axiom.tool.biome_painter", wire: "axiom.tool.biome_painter", parent: Some(55) },
    Perm { node: "axiom.tool.gradient_painter", wire: "axiom.tool.gradient_painter", parent: Some(55) },
    Perm { node: "axiom.tool.script_brush", wire: "axiom.tool.script_brush", parent: Some(55) },
    Perm { node: "axiom.tool.freehand_draw", wire: "axiom.tool.freehand_draw", parent: Some(55) },
    Perm { node: "axiom.tool.sculpt_draw", wire: "axiom.tool.sculpt_draw", parent: Some(55) },
    Perm { node: "axiom.tool.rock", wire: "axiom.tool.rock", parent: Some(55) },
    Perm { node: "axiom.tool.weld", wire: "axiom.tool.weld", parent: Some(55) },
    Perm { node: "axiom.tool.melt", wire: "axiom.tool.melt", parent: Some(55) },
    Perm { node: "axiom.tool.stamp", wire: "axiom.tool.stamp", parent: Some(55) },
    Perm { node: "axiom.tool.text", wire: "axiom.tool.text", parent: Some(55) },
    Perm { node: "axiom.tool.shape", wire: "axiom.tool.shape", parent: Some(55) },
    Perm { node: "axiom.tool.path", wire: "axiom.tool.path", parent: Some(55) },
    Perm { node: "axiom.tool.modelling", wire: "axiom.tool.modelling", parent: Some(55) },
    Perm { node: "axiom.tool.floodfill", wire: "axiom.tool.floodfill", parent: Some(55) },
    Perm { node: "axiom.tool.fluidball", wire: "axiom.tool.fluidball", parent: Some(55) },
    Perm { node: "axiom.tool.elevation", wire: "axiom.tool.elevation", parent: Some(55) },
    Perm { node: "axiom.tool.slope", wire: "axiom.tool.slope", parent: Some(55) },
    Perm { node: "axiom.tool.smooth", wire: "axiom.tool.smooth", parent: Some(55) },
    Perm { node: "axiom.tool.distort", wire: "axiom.tool.distort", parent: Some(55) },
    Perm { node: "axiom.tool.roughen", wire: "axiom.tool.roughen", parent: Some(55) },
    Perm { node: "axiom.tool.shatter", wire: "axiom.tool.shatter", parent: Some(55) },
    Perm { node: "axiom.tool.extrude", wire: "axiom.tool.extrude", parent: Some(55) },
    Perm { node: "axiom.tool.modify", wire: "axiom.tool.modify", parent: Some(55) },
    Perm { node: "axiom.builder_tool.*", wire: "axiom.builder_tool.*", parent: Some(15) },
    Perm { node: "axiom.builder_tool.move", wire: "axiom.builder_tool.move", parent: Some(87) },
    Perm { node: "axiom.builder_tool.clone", wire: "axiom.builder_tool.clone", parent: Some(87) },
    Perm { node: "axiom.builder_tool.stack", wire: "axiom.builder_tool.stack", parent: Some(87) },
    Perm { node: "axiom.builder_tool.smear", wire: "axiom.builder_tool.smear", parent: Some(87) },
    Perm { node: "axiom.builder_tool.extrude", wire: "axiom.builder_tool.extrude", parent: Some(87) },
    Perm { node: "axiom.builder_tool.erase", wire: "axiom.builder_tool.erase", parent: Some(87) },
    Perm { node: "axiom.builder_tool.setup_symmetry", wire: "axiom.builder_tool.setup_symmetry", parent: Some(87) },
];
